![alt text](https://secure.meetupstatic.com/photos/event/c/9/7/a/600_487911578.jpeg)

Week 4 Assignment

Data Scientist are Sexy. But to maintain it, we need skincare products!
This week we will explore a dataset from Sephora with skincare products.
Your tasks is to predict if a product is HOT or NOT.
We will determine this by the rating column.

We provided 2 dataframe: Train and Test. Notice that the test doesn't have the column "rating". 

You tasks is to build a model which predicts the rating of the test data (binary classification). Use the train dataset for training the model.
You are free to use any model.


Submit your ipynb on Google Forms.
[https://forms.gle/qJzy4S1RadiFtdu3A](https://forms.gle/qJzy4S1RadiFtdu3A)

In [3]:
!pip install rfpimp

Requirement already satisfied: rfpimp in /usr/local/lib/python3.6/dist-packages (1.3.4)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.6/dist-packages (from rfpimp) (3.2.1)
Requirement already satisfied: sklearn in /usr/local/lib/python3.6/dist-packages (from rfpimp) (0.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.6/dist-packages (from rfpimp) (1.0.3)
Requirement already satisfied: numpy in /usr/local/lib/python3.6/dist-packages (from rfpimp) (1.18.3)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python3.6/dist-packages (from matplotlib->rfpimp) (2.4.7)
Requirement already satisfied: python-dateutil>=2.1 in /usr/local/lib/python3.6/dist-packages (from matplotlib->rfpimp) (2.8.1)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.6/dist-packages (from matplotlib->rfpimp) (1.2.0)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.6/dist-packages (from matplotlib->rfpimp) (0.10.0)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.6/dist-packages (from sklearn->rfpimp) (0.22.2.post1)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.6/dist-packages (from pandas->rfpimp) (2018.9)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.6/dist-packages (from python-dateutil>=2.1->matplotlib->rfpimp) (1.12.0)
Requirement already satisfied: scipy>=0.17.0 in /usr/local/lib/python3.6/dist-packages (from scikit-learn->sklearn->rfpimp) (1.4.1)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.6/dist-packages (from scikit-learn->sklearn->rfpimp) (0.14.1)

In [4]:
!wget https://www.mlgraz.at/course_files/week4/train.csv

--2020-04-27 19:15:43--  https://www.mlgraz.at/course_files/week4/train.csv
Resolving www.mlgraz.at (www.mlgraz.at)... 81.19.159.92
Connecting to www.mlgraz.at (www.mlgraz.at)|81.19.159.92|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 867803 (847K) [text/csv]
Saving to: ‘train.csv.1’

train.csv.1         100%[===================>] 847.46K  1.43MB/s    in 0.6s

2020-04-27 19:15:44 (1.43 MB/s) - ‘train.csv.1’ saved [867803/867803]

In [5]:
!wget https://www.mlgraz.at/course_files/week4/test.csv

--2020-04-27 19:15:47--  https://www.mlgraz.at/course_files/week4/test.csv
Resolving www.mlgraz.at (www.mlgraz.at)... 81.19.159.92
Connecting to www.mlgraz.at (www.mlgraz.at)|81.19.159.92|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 104445 (102K) [text/csv]
Saving to: ‘test.csv’

test.csv            100%[===================>] 102.00K   296KB/s    in 0.3s

2020-04-27 19:15:48 (296 KB/s) - ‘test.csv’ saved [104445/104445]

In [0]:
import pandas as pd
from sklearn.impute import SimpleImputer
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from  sklearn.preprocessing import OrdinalEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_validate
from  sklearn.metrics import *
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn import tree
from sklearn import model_selection
import plotly.express as px

In [7]:
import rfpimp

/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:144: FutureWarning:

The sklearn.ensemble.forest module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.ensemble. Anything that cannot be imported from sklearn.ensemble is now part of the private API.

In [0]:
df_train = pd.read_csv("train.csv")
df_test = pd.read_csv("test.csv")

In [9]:
df_train.head()

   Unnamed: 0           brand  ... limited_time_offer likes
0           0  Acqua Di Parma  ...                  0  3002
1           1  Acqua Di Parma  ...                  0  2700
2           2  Acqua Di Parma  ...                  0  2600
3           4  Acqua Di Parma  ...                  0   943
4           5  Acqua Di Parma  ...                  0  2600

[5 rows x 15 columns]

In [10]:
df_test.head()

   Unnamed: 0         brand  ... limited_time_offer  likes
0        3941    Jack Black  ...                  0    311
1        3064         Fresh  ...                  0   5100
2        8281      TOM FORD  ...                  0    897
3        6413  Perricone MD  ...                  0  11600
4        1302      Caudalie  ...                  0      0

[5 rows x 14 columns]

In [11]:
df_train.shape

(8168, 15)

In [12]:
df_test.shape

(1000, 14)

In [0]:
df_train = df_train.drop("Unnamed: 0", axis=1)
df_test = df_test.drop("Unnamed: 0", axis=1)

In [0]:
df_train = df_train.drop("MarketingFlags", axis=1)
df_test = df_test.drop("MarketingFlags", axis=1)

In [0]:
df_train = df_train.drop("MarketingFlags_content", axis=1)
df_test = df_test.drop("MarketingFlags_content", axis=1)

In [16]:
df_train.head()

            brand   category  ... limited_time_offer  likes
0  Acqua Di Parma  Fragrance  ...                  0   3002
1  Acqua Di Parma    Cologne  ...                  0   2700
2  Acqua Di Parma    Perfume  ...                  0   2600
3  Acqua Di Parma  Fragrance  ...                  0    943
4  Acqua Di Parma    Perfume  ...                  0   2600

[5 rows x 12 columns]

In [17]:
df_test.head()

          brand           category  ... limited_time_offer  likes
0    Jack Black             Toners  ...                  0    311
1         Fresh       Moisturizers  ...                  0   5100
2      TOM FORD  Deodorant for Men  ...                  0    897
3  Perricone MD            Bronzer  ...                  0  11600
4      Caudalie          Mini Size  ...                  0      0

[5 rows x 11 columns]

In [0]:
categorical_columns = ["brand", "category", "name"]

In [0]:
for col in categorical_columns:
    df_train[col] = df_train[col].astype('category')

In [0]:
df_train = pd.get_dummies(df_train, drop_first=True)

In [0]:
for col in categorical_columns:
    df_test[col] = df_test[col].astype('category')

In [0]:
df_test = pd.get_dummies(df_test, drop_first=True)

In [23]:
df_train.head()

   rating  ...  name_’REPLICA’ Sailing Day Travel Spray
0       1  ...                                        0
1       1  ...                                        0
2       1  ...                                        0
3       0  ...                                        0
4       1  ...                                        0

[5 rows x 8589 columns]

In [24]:
df_test.head()

   number_of_reviews  ...  name_’REPLICA’ Music Festival
0                  3  ...                              0
1                 39  ...                              0
2                  9  ...                              0
3                196  ...                              0
4                  3  ...                              0

[5 rows x 1349 columns]

In [0]:
col_list = list(set().union(df_test.columns, df_train.columns))

In [26]:
len(col_list)

9578

In [0]:
def add_missing_dummy_columns( d, columns ):
    missing_cols = set( columns ) - set( d.columns )
    for c in missing_cols:
        d[c] = 0

In [0]:
add_missing_dummy_columns(df_test, col_list)

In [0]:
add_missing_dummy_columns(df_train, col_list)

In [30]:
df_test.drop("rating", axis=1)

     number_of_reviews  price  ...  name_Oud Fleur  name_Retouching Face Pencil
0                    3   25.0  ...               0                            0
1                   39  148.0  ...               0                            0
2                    9   53.0  ...               0                            0
3                  196   35.0  ...               0                            0
4                    3   24.0  ...               0                            0
..                 ...    ...  ...             ...                          ...
995                 54   39.0  ...               0                            0
996                 38   60.0  ...               0                            0
997               1000   36.0  ...               0                            0
998                 10   42.0  ...               0                            0
999                  4   55.0  ...               0                            0

[1000 rows x 9577 columns]

In [0]:
X = df_train.loc[:, df_train.columns != 'rating']

In [0]:
y = df_train["rating"]

In [0]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [34]:
model=DecisionTreeClassifier()
model.fit(X_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [0]:
y_pred = model.predict(X_test)

In [36]:
accuracy_score(y_test, y_pred)

0.7978486646884273

In [37]:
precision_score(y_test, y_pred)

0.8373983739837398

In [38]:
recall_score(y_test, y_pred)

0.9222431668237512

In [39]:
f1_score(y_test, y_pred)

0.8777752859385513

In [0]:
df_test = df_test.drop("rating", axis=1)

In [0]:
y_pred_test = model.predict(df_test)

In [0]:
df_test["rating"] = y_pred_test

In [43]:
df_test.rating.value_counts()

1    886
0    114
Name: rating, dtype: int64